### ISSUE TITLE
document the meta.yaml build/noarch_python attribute

### ISSUE THREAD

**Issue by jasongrout** [conda/conda-docs#181]
This attribute appears now in  pypi skeleton files, but you have to go to the source or the PR introducing it to really understand what it is doing.

**Comment by jasongrout** [comment]
FYI, the PR is at https://github.com/conda/conda-build/pull/317

**Comment by electronwill** [comment]
@ilanschnell , I'm cleaning up old issues and it looks like the noarch_python attribute made it into the code but no docs change was ever made. Would you please make a PR adding it to the docs and @-tag me?

**Comment by electronwill** [comment]
Added by @AlbertDeFusco in https://github.com/conda/conda-docs/pull/288 .
