### ISSUE TITLE
table "conda vs. pip vs. virtualenv" : missing argument for conda update

### ISSUE THREAD

**Issue by alaindomissy** [conda/conda-docs#185]
page http://conda.pydata.org/docs/_downloads/conda-pip-virtualenv-translator.html currently shows :

Task	 | Conda package and environment manager command
-------|-------------------------------------------------------------------------
Update a package |	conda update --name $PACKAGE_NAME
but it should be :

Task | Conda package and environment manager command
-------|-------------------------------------------------------------------------
Update a package |	conda update --name $ENVIRONMENT_NAME $PACKAGE_NAME

I would do a pull request, but I can not find that page on github. Thanks.

**Comment by asmeurer** [comment]
I think it is https://github.com/conda/conda-docs/blob/master/docs/source/help/conda-pip-virtualenv-translator.rst.

**Comment by electronwill** [comment]
Should be fixed by https://github.com/conda/conda-docs/pull/205
