### ISSUE TITLE
default_channels undocumented

### ISSUE THREAD

**Issue by bkreider** [conda/conda-docs#219]
It looks like the "default_channels" configuration value for .condarc, lets you redefine where the "defaults" alias points to.

**Comment by electronwill** [comment]
@ilanschnell http://conda.pydata.org/docs/config.html#channel-locations-channels says that Anaconda Cloud usernames, http:// and file:/// URIs, and "defaults" are all valid values for the "channels" option. Are all four of those also valid values for the "default_channels" option?

If so, I will add this information about default_channels to http://conda.pydata.org/docs/install/central.html#system-configuration-settings .

```
channels:
  - <anaconda_dot_org_username>
  - http://some.custom/channel
  - file:///some/local/directory
  - defaults
```

**Comment by electronwill** [comment]
Sorry for the delay, but Kale's help was instrumental in finishing this. Fixed in https://github.com/conda/conda-docs/pull/224 .
