### ISSUE TITLE
Replace old cheat sheet with revised one

### ISSUE THREAD

**Issue by kerrywatson1** [conda/conda-docs#228]
The old conda cheat sheet appears to be here: 
http://conda.pydata.org/docs/_downloads/conda-cheatsheet.pdf

Needs to be replaced with the revised cheat sheet,
[Conda-Cheat-Sheet-PDF.pdf](https://github.com/conda/conda-docs/files/86175/Conda-Cheat-Sheet-PDF.pdf)
 attached.

**Comment by electronwill** [comment]
OK, done.
