### ISSUE TITLE
Size increase of docs/source/using/conda-cheatsheet.pdf

### ISSUE THREAD

**Issue by jfbu** [conda/conda-docs#239]
No doubt a minor issue, but after a long overdue git pull, I got:

```bash
conda-docs$ git pull
[....]
From https://github.com/conda/conda-docs
   2e14d21..7122f68  master     -> origin/master
   5cac318..b2379d7  gh-pages   -> origin/gh-pages
Updating 2e14d21..7122f68
Fast-forward
 [...]
 docs/source/using/conda-cheatsheet.pdf  | Bin 118159 -> 794349 bytes
 15 files changed, 158 insertions(+), 119 deletions(-)
```
When I compare the two conda-cheatsheet.pdf files  I see little difference (lines added about *Build a Conda package from a Python Package (PyPI) Package*) and some more green color in the recent one. Both produced by *Adobe Illustrator CC 2015, Adobe PDF library 15.00*.

I checked the fonts, and it appears the same font family is used, with the addition of the Medium variant. I know my question is a bit ridiculous. But I always wonder about file sizes !

**Comment by electronwill** [comment]
Sorry for the slow reply. It turns out the latest version uses less compression, so it has a larger file size but looks sharper.

**Comment by jfbu** [comment]
@electronwill thanks for the explanation... a famous quote of mathematician David Hilbert says Wir müssen wissen — wir werden wissen! https://en.wikipedia.org/wiki/Ignoramus_et_ignorabimus (we must know, we will know !), and although I generally strongly disagree with that, at times in matters of computers I can get very frustrated in front of unexplained phenomena.

**Comment by electronwill** [comment]
I know the feeling! Computers can produce a lot of certain things very quickly, and unexplained phenomena are high on the list.
