### ISSUE TITLE
Travis tutorial not working with SciPy

### ISSUE THREAD

**Issue by douglasrizzo** [conda/conda-docs#240]
I just followed the [Using conda with Travis CI](https://github.com/conda/conda-docs/blob/master/docs/source/travis.rst) tutorial. In fact, my own `.travis.yml` file is [right here](https://github.com/douglasrizzo/catsim/blob/19fb41187522d7b80aa2bbfe6f1dab1452bedb2a/.travis.yml).

After installing my own package, when running `nosetests`, I am presented with the following message:

    Failure: ImportError (No module named 'scipy')

Is there a problem in the tutorial? Or did I do something wrong?

**Comment by electronwill** [comment]
Sorry for the slow reply on this one.

It looks like the "install" and "script" sections of the travis.yml file are separate, so the environment created and activated in "install" isn't still active when the "script" section starts. What happens if the "source activate test-environment" command is added to the start of the "script" section?

**Comment by douglasrizzo** [comment]
I've actually fixed this a few months ago. It turns out that calling `nosetests` in the Travis VM actually uses a default installation of nose that comes preinstalled with the VM. This version of nose can't find scipy because nose is outside Miniconda's virtualenv. In my new [travis.yml file](https://github.com/douglasrizzo/catsim/blob/c0b0735c7412a55e9b855800bc234f2602f661c7/.travis.yml), I install nose manually using `pip`, inside the virtualenv created with Miniconda. It replaces the default installation of nose and everything works fine.

**Comment by electronwill** [comment]
Excellent! In the future we'll be sure to reply more quickly, and I'm very glad to hear it's working.
