### ISSUE TITLE
"from scratch" should be from scratch

### ISSUE THREAD

**Issue by jni** [conda/conda-docs#245]
The [from scratch](http://conda.pydata.org/docs/build_tutorials/pkgs2.html) page on how to build a conda recipe begins by saying we will copy an existing (or rather [non-existent](https://github.com/conda/conda-recipes/issues/606)) recipe. I actually find it quite difficult to follow such a tutorial because I end up not understanding what I'm doing. Hence [this](https://github.com/conda/conda-build/issues/791). =P

**Comment by electronwill** [comment]
Good point. As soon as we can get noarch_python documented as discussed in https://github.com/conda/conda-docs/issues/181 , I should review the "from scratch" recipe and make sure we're giving correct instructions. Affects this issue and https://github.com/conda/conda-recipes/issues/606 .

**Comment by rrigdon** [comment]
This doc has been updated: https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html
