### ISSUE TITLE
typo: test-drive parentheses/brackets mix up

### ISSUE THREAD

**Issue by kbrose** [conda/conda-docs#246]
The test drive file ([https://github.com/conda/conda-docs/blob/master/docs/source/test-drive.rst](https://github.com/conda/conda-docs/blob/master/docs/source/test-drive.rst)) section two states 

```rst
Conda displays the list of all environments, with the current environment shown in (parentheses) in front of your prompt:

.. code::

   (snowflakes)
```

but with conda version 3.19 on windows, it instead shows the current environment name with brackets, i.e.

```rst
Conda displays the list of all environments, with the current environment shown in [brackets] in front of your prompt:

.. code::

   [snowflakes]

**Comment by electronwill** [comment]
Oh-- looks like this varies between platforms. Thank you for pointing that out! Fixed in https://github.com/conda/conda-docs/pull/248 .
