### ISSUE TITLE
((double parentheses)) after conda PR 1727

### ISSUE THREAD

**Issue by electronwill** [conda/conda-docs#249]
When 'conda info -e' starts using ((double parentheses)) around the active environment, correct the test drive to say so, as explained in https://github.com/conda/conda-docs/pull/248 and https://github.com/conda/conda/pull/1727 .

**Comment by electronwill** [comment]
@msarahan so glad to see this is merged! Do you know when the next conda release will go out so that users will start seeing this behavior?

**Comment by msarahan** [comment]
I think the dust should settle from the recent 4.0.x series.  I'm fairly confident in 1727, but I really don't want to add fuel to the fire right now.  It'll be up to @kalefranz's judgement when we're ready (and perhaps there will be a beta/test version before an official release).

**Comment by electronwill** [comment]
Looks like conda 4.1 may wind up saving and restoring the path without using any regular expressions, so it's not certain whether the move to double parentheses will happen. Closing this for now, although if the change does happen, I'll remember to update the docs to match.
