### ISSUE TITLE
Main docs page out of date

### ISSUE THREAD

**Issue by bryevdv** [conda/conda-docs#260]
The main doc page at conda.pydata.org is out of date, mentioning "Anaconda Pro" etc. Additionally, WRT to relations to paid products, suggest that the page only have one sentence with a link to a CIO hosted page for those integrations. This is not the right place for product advertisement.

**Comment by electronwill** [comment]
I believe Pro/Workgroup/Enterprise are the correct current names, based on the Subscriptions page: https://www.continuum.io/anaconda-subscriptions

Good points about adding a link and trimming the advertising. Fixed in https://github.com/conda/conda-docs/pull/262
