### ISSUE TITLE
Document expected use of post/pre un/link scripts

### ISSUE THREAD

**Issue by bollwyvl** [conda/conda-docs#289]
If you've got it, you're going to use it. Let's document how these parts of the `conda [un]install` lifecycle should play out. Perhaps if some stronger language existed, we would not have gone down this path on the various nbextensions

>> _From https://github.com/conda-forge/conda-forge.github.io/issues/173_

> @ilanschnell When post-link scripts output things, it is probably important (usually some error message). In this case, the post-link script is used in a way that it was never designed for. I think we have to better communicate the purpose of these scripts.

> Post-link (and pre-unlink) scripts should:
1.) be avoided whenever possible
2.) not touch anything other than the files being installed
3.) not write anything to stdout (or stderr), unless an error occurs
4.) not depend on any installed (or to be installed) conda packages
5.) only depend on simple system tools rm, cp, mv, ln, etc.

**Comment by ilanschnell** [comment]
Thanks.  I am going to talk to @electronwill today, to see where the best place for this information is.

**Comment by electronwill** [comment]
Looks like our existing page on pre/post link/unlink scripts is very brief and could definitely benefit from this addition.

http://conda.pydata.org/docs/building/build-scripts.html
https://github.com/conda/conda-docs/blob/master/docs/source/building/build-scripts.rst

**Comment by electronwill** [comment]
OK, these changes are deployed.

**Comment by bollwyvl** [comment]
That's awesome, thanks, guys!
