### ISSUE TITLE
json-c package is missing on the channel jlaura

### ISSUE THREAD

**Issue by oinizan** [conda/conda-docs#309]
Adding the channel jlaura for json-c dependency has no effect.
The package json-c is still missing when I run conda build:

`~/postgis$ conda build .`

Here is the output:

```
Fetching package metadata ...........
Solving package specifications: .
Error: Package missing in current linux-64 channels: 

```

**Comment by electronwill** [comment]
The postgis conda tutorial at http://conda.pydata.org/docs/build_tutorials/postgis.html depends on the json-c package from Anaconda Cloud account jlaura, and it appears this account has removed all files from this package. https://anaconda.org/jlaura/json-c What's the best way to handle this? Can we get json-c into some other more stable channel and fix the tutorial to point there? @kalefranz @msarahan

**Comment by xakiv** [comment]
Hi @electronwill ! Did you reach any solution for this issue? I am stuck at the same point then you... Thank's for your help

**Comment by electronwill** [comment]
Conda forge seems to have packages built for linux 64 and osx: https://anaconda.org/conda-forge/json-c

A search at https://anaconda.org/search?q=json-c shows a few other linux 64 versions but no linux 32 versions. Possibly contacting conda forge about making a linux 32 version, and then changing the tutorial to use that, would be the best option. I'll discuss this further with the conda devs as soon as I can and reply here with more information.

**Comment by mingwandroid** [comment]
Until conda defaults and conda-forge are binary compatible I would rather never mention conda-forge in our docs in terms of as a channel to fetch software from where that software is to be installed alongside software from defaults.

I spend too much time helping users who have mixed the channels and ended up unable to run things as it is.

I'm happy to add packages you need. @csoja?

**Comment by csoja** [comment]
I'd agree - we should add this package to repo.continuum.io - or another Anaconda Cloud channel  - maybe a new organization called anaconda-tutorials (or if another organization already exists where we put tutorial notebooks, have the packages added to that channel too)?

**Comment by electronwill** [comment]
Thank you very much @mingwandroid and @csoja !

I appreciate the warning about not installing software from default channels alongside software from the conda-forge channel; I hadn't realized they weren't currently binary compatible.

json-c is the only package used in the conda tutorials that is not already in the default channels. I'm not aware of any already existing organization for tutorial notebooks, and either a new "anaconda-tutorials" organization or an existing organization sound great to me. Adding the json-c package to the default channels would solve the whole problem perfectly.

**Comment by electronwill** [comment]
@mingwandroid , any estimate on when we could see a json-c package in the default channels?

**Comment by mingwandroid** [comment]
Maybe mid-Feb?

**Comment by electronwill** [comment]
OK, we'll leave this one on the back burner for now.
