### ISSUE TITLE
conda-build seems not to be installed on miniconda version

### ISSUE THREAD

**Issue by oinizan** [conda/conda-docs#310]
The doc says:

> Miniconda is a small “bootstrap” version that includes only conda and conda-build, and installs Python. Over 720 scientific packages and their dependencies can be installed individually from the Continuum repository with the “conda install” command.

But after a miniconda download and install, the conda build command fails:

```
conda build --help
Error: You need to install conda-build in order to use the 'conda build'
       command.

```

**Comment by msarahan** [comment]
This seems like a documentation error - thanks for raising it.  I don't think miniconda should include conda-build.  @electronwill

**Comment by electronwill** [comment]
Yes, thank you for pointing this out. A quick test confirms that Miniconda does not include conda-build. Fixed in https://github.com/conda/conda-docs/pull/311 .
