### ISSUE TITLE
Add Changelog page on docs

### ISSUE THREAD

**Issue by kalefranz** [conda/conda-docs#313]
Need a changelog page on conda.pydata.org/docs.  I guess it'll need to be its own, new page.
Mostly just copy https://github.com/conda/conda/blob/master/CHANGELOG.txt
Another possibility would be to copy https://github.com/conda/conda/releases which has the issue/PR linking already done.

Be sure to leave off any unreleased changes (right now 4.2.0).

**Comment by electronwill** [comment]
Done in https://github.com/conda/conda-docs/pull/316 .
