### ISSUE TITLE
Add PY_VER

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-docs#330]
Appears `PY_VER` is missing from the `conda-build` [environment variables](http://conda.pydata.org/docs/building/environment-vars.html) in the docs. It should be added.

cc @msarahan

**Comment by tadeu** [comment]
It's already in https://conda.io/projects/conda-build/en/latest/source/environment-variables.html#environment-variables-set-during-the-build-process, so this issue can probably be closed :)
