### ISSUE TITLE
Remove my channel from .travis.yml

### ISSUE THREAD

**Issue by asmeurer** [conda/conda-docs#340]
My channel is currently being used in the .travis.yml to install several things. While I do not plan to remove any packages from my channel, I would recommend moving all the packages that are used to the official defaults channel, or to conda-forge, and use that instead. I no longer maintain my own channel, preferring to use conda-forge instead. The recipes for every package should be in conda-recipes. 

There is a metapackage `conda-docs-deps`, which you might want to replace with a conda-env file (or else upload the metapackage to some Continuum-owned channel).

**Comment by asmeurer** [comment]
OK, that's not entirely true. I don't know where the continuum-sphinx-theme is. It's in a private repo maybe?

**Comment by electronwill** [comment]
Good points, and thank you for mentioning this. You're right, it would be better to use defaults or conda-forge. It looks like the continuum-sphinx-theme is currently in the private docs repo at https://github.com/ContinuumIO/docs/tree/master/build/_themes/continuum . I'm not sure if that's the one used in the conda docs or a copy. I think it would be best to replace conda-docs-deps with a conda-env file, and it would also be OK put the metapackage in another channel instead. I'll reply further on #339 .

**Comment by asmeurer** [comment]
I believe some of the packages will need to be built either by Continuum or added to conda-forge. In particular, help2man and man2html (which are used to put the conda help pages in the docs), both of which use perl. Or if you want you could try moving to one of [these](http://stackoverflow.com/q/10886841/161801) (I don't recall, but I probably tried them myself when I set this up and I wasn't satisfied).

**Comment by msarahan** [comment]
Ready to close this, right?

**Comment by msarahan** [comment]
Never mind, I guess I'll rebuild your packages and doctr before closing this.
