### ISSUE TITLE
Mailing list too prominently displayed?

### ISSUE THREAD

**Issue by jakevdp** [conda/conda-docs#344]
On http://conda.pydata.org, the first thing a user sees is a large mailing list signup. This is not typical for an open source project, and probably does a lot to contribute to the prevalence of the misconception that conda is a proprietary platform.

Would it be possible to move/remove that form from the landing page, and instead have more prominently outline the ways to install conda?

**Comment by electronwill** [comment]
I see what you mean. What do you think @kalefranz ?
