### ISSUE TITLE
Clarify Feature usage and update for nomkl instead of mkl

### ISSUE THREAD

**Issue by timsnyder** [conda/conda-docs#372]
The [Features 'section'](http://conda.pydata.org/docs/building/meta-yaml.html#id1) pointed to by several of the meta.yaml sections (e.g. [build.Features](http://conda.pydata.org/docs/building/meta-yaml.html#features)) is still written with the assumption that 'nomkl' is the default.  However, that behavior changed earlier this year with [Anaconda 2.5](https://www.continuum.io/blog/developer-blog/anaconda-25-release-now-mkl-optimizations)

While this isn't the most dire of issues, newcomers to conda-build may find it highly confusing.  

Also, now that [continuumio/anaconda-recipes](https://github.com/ContinuumIO/anaconda-recipes) exists, perhaps the Features section could link to some examples of it's usage in there?  I'm happy to submit a PR for this.

**Comment by electronwill** [comment]
I agree, fixing the assumption that 'nomkl' is default is well worth while.

@kalefranz or @msarahan adding examples of using anaconda-recipes to the Features section seems like a great idea to me-- do you agree?
