### ISSUE TITLE
Can't install miniconda with the "Traceback (most recent call last)" issue

### ISSUE THREAD

**Issue by xuechunxu** [conda/conda-docs#382]
Dear all,
I tried to install Miniconda, but it can't work after finish all the steps.
when I close and re-open the terminal windows ,and enter the command "conda list".
It printed something below:

> 
![image](https://cloud.githubusercontent.com/assets/23622076/20596838/6425a1a0-b27b-11e6-97fa-15e6f8f8e2ef.png)
I don't have any idea about this, anyone help me?
Best wish!

**Comment by ChenyuanZ** [comment]
Did you add the path to conda in your $PATH?

**Comment by xuechunxu** [comment]
I forget it. I will checked tommorrow



发自我的小米手机
在 Chenyuan <notifications@github.com>，2017年8月29日 下午10:08写道：

Did you add the path to conda in your $PATH?
