### ISSUE TITLE
msvc_compiler meta.yml conda-build option is not documented

### ISSUE THREAD

**Issue by xantares** [conda/conda-docs#392]

**Comment by scw** [comment]
Bump on this one. `conda build` is currently emitting this message:

> Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0.  Use {{compiler('c')}} jinja2 in requirements/build or explicitly list compiler package as build dependency instead.
WARNING:conda_build.windows:Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0.  Use {{compiler('c')}} jinja2 in requirements/build or explicitly list compiler package as build dependency instead.

That message doesn't make it clear how to "explicitly list [the] compiler package", and having a relevant section in the documentation would be helpful.

**Comment by msarahan** [comment]
Sorry about that message.  I need to fix it.  Long-term, msvc_compiler is going away.  It's getting replaced by compiler specification with conda-build 3's new style.  There's a blog post explaining it at https://www.continuum.io/blog/developer-blog/package-better-conda-build-3

We have compiler packages for the various visual studio things at 
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2008
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2010
https://github.com/AnacondaRecipes/aggregate/tree/master/vs2015

and https://anaconda.org/c3i_test
