### ISSUE TITLE
Docs for py selector claim it is a two digit string

### ISSUE THREAD

**Issue by msarahan** [conda/conda-docs#394]
@scopatz commented on [Thu Jan 05 2017](https://github.com/conda/conda-build/issues/1622)

but `py` acts like an integer since you can do `py >= 35` and other numeric comparisons. I suspect that this is wrong.

see http://conda.pydata.org/docs/building/meta-yaml.html#preprocessing-selectors

**Comment by scopatz** [comment]
Didn't know this repo existed. Should I open doc issues here in the future, @msarahan?

**Comment by msarahan** [comment]
Yes, please, unless it is a bad docstring.  Those should be kept where the source is.  This is the repo for the source that makes conda.pydata.org/docs

**Comment by scopatz** [comment]
Will do

**Comment by jakirkham** [comment]
Probably should mention issue ( https://github.com/conda/conda-build/issues/1202 ).

**Comment by rrigdon** [comment]
This claim is no longer in the docs.
