### ISSUE TITLE
command line documentation formatting

### ISSUE THREAD

**Issue by electronwill** [conda/conda-docs#41]
Based on a suggestion from @jklowden :

Commands like 'conda --help' and 'conda create --help' often produce text without formatting that could be beneficial, and with lines shorter or longer than they should be, especially on Windows. We could benefit from using formatting more like the manual pages produced by commands such as 'man ls'.

We could fix this by using the groff tools, which would generate PDF, HTML, and man pages. Failing that, we could follow the example of 'git --help', which opens a browser window with a web page or local HTML file to show the formatted documentation.

This change could also incorporate @asmeurer 's idea to ensure that asking for help with a command also shows the help for its subcommands:

https://github.com/conda/conda-build/issues/368

Here are James Lowden's original comments; there were also three attachments which I can upload as well, a screenshot, a pdf, and a file 'conda-create.1'.

On Mon, Mar 23, 2015 at 5:32 PM, James Lowden wrote:
Hi Kerry,
 
First of all, let me say how glad I am we’ve hired someone to work on our documentation.  Documentation was one of the first things I mentioned to Travis when I started with Continuum. 
 
Second, I’d like to suggest a way to improve our command-line help by using an old, long-ported tool designed to do the job: groff. 
 
I ran conda create –help today and found the text all but unreadable, see below image.  In an attempt to be constructive, I composed a standard man page from the text, with very few changes.  (It could still use a push in the direction of the king’s English.) 
 
Please note my version cannot be used verbatim.  The –help option evidently is a little bit dynamic; where the environment name should be represented as substitutable parameter, in my page the name of my environment, neat, appears. 
 
I think you’ll agree the PDF is easier to read than the almost unformatted text produced by –help.  If you install the .1 file to e.g. /usr/share/man/man1 (or use man ./conda-create.1) in Linux, I think you’ll also agree that is easier to read, even without the full typographic benefit afforded by Postscript. 
 
The question is: How do we provided better help (and on-line documentation) for our command-line tools? 
 
I would like to suggest we use the groff tools.  That would let us generate PDF, HTML, and reasonable man pages for Linux and OS X.  Groff has been ported to Windows, and would help us improve the appearance of –help.  Git used to do that; git-foo --help would invoke groff and put a man page in GNU less for you. 
 
I know we’re a Python shop, and all Python shops are bound to use Sphinx.  In the case of the command-line help and documentation, I suggest that’s insufficient to the task.  The groff mdoc markup language looks weird at first, but in the end it’s actually the simplest markup toolchain I’ve used, and specifically designed for this kind of documentation. 
 
If we don’t want to emulate man on Windows, there are a couple of other options:
 
·         Use groff to generate formatted text from mdoc sources, and embed that text in the Python for display.  Possibly also include escape sequences to supply boldface and underlining.  At least this would produce lines of no more than 80 characters, making the text easier for the eye to scan. 

·         Use groff to generate PDFs (or HTML) and embed that in the Python or a database of same, and have conda foo –help invoke a web browser.  That’s what git does.  Not my favorite option, but better than what we’re doing now. 

I hope you find the above helpful.  Happy to discuss at your convenience. 
 
Regards,
 
--jkl

**Comment by electronwill** [comment]
![image001](https://cloud.githubusercontent.com/assets/12059307/7483551/6a15729e-f345-11e4-976d-f466dd029f4e.png)

**Comment by asmeurer** [comment]
We do generate man pages as part of the [documentation build process](https://github.com/conda/conda-docs/blob/master/docs/scrape_help.py) but they are currently only used to generate the html pages at http://conda.pydata.org/docs/commands.html. The tools help2man, man (effectively groff), and man2html are used here. The `--help` output itself is generated automatically by argparse.  I'm not sure why it isn't line wrapping the help output. @jklowden can you tell me what shell you are using and show me your `conda info`?

There has been discussion on shipping these man pages with conda. The main question is how to get man to find them, since it won't look in the anaconda/share/man directory by default. 

At the end of the day, we do have the output of all `--help` at http://conda.pydata.org/docs/commands.html, which should suffice for most purposes.

**Comment by asmeurer** [comment]
I can't reproduce the non-word wrapping.
