### ISSUE TITLE
meta.yaml field not documented : `source: fn:`

### ISSUE THREAD

**Issue by c-f-h** [conda/conda-docs#426]
Many recipes seem to use a field

```
source:
    fn:
```

Yet I can find no documentation for this at https://conda.io/docs/building/meta-yaml.html .

**Comment by kerrywatson1** [comment]
Heavily documented now in https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html

Closing.

**Comment by electronwill** [comment]
@kalefranz I see a lot about "source:" but nothing about "fn:". Is this done?

**Comment by kalefranz** [comment]
It does look like `source: / fn:` is a valid key, according to `conda_build/metadata.py`.  Would want @msarahan to confirm that indeed is true.

**Comment by msarahan** [comment]
It is a valid key. It used to be required with URL source types. It is not required anymore. If provided, it determines the filename of the saved file on disk. When not provided, it is the final but if the URL.

For example,

Http://www.something.com/myfile.zip

Has an implicit fn of myfile.zip, and users may change this by manually specifying fn.

**Comment by kalefranz** [comment]
Oh right.  Thanks for the clarification.  I had forgotten that it used to be required.

**Comment by electronwill** [comment]
Fixed in https://github.com/conda/conda-docs/pull/501 . Thank you very much, @kalefranz and @msarahan .
