### ISSUE TITLE
install_requires in  setup.py vs meta.yaml requirements

### ISSUE THREAD

**Issue by arsenovic** [conda/conda-docs#435]
hi, 
 i am conda-building a [package](https://github.com/scikit-rf/scikit-rf/blob/master/setup.py) that has a setup.py. i have used `install_requires` option in setup(), to keep track of my package's run-time dependencies. however, `meta.yaml` has both a `install` and `run` requirements. my question is: since conda-build will  install my package by running `setup.py`, which contains run-time dependencies in `install_requires`, how are `run` and `install` sections in `meta.yaml` different?

**Comment by msarahan** [comment]
There is no "install" section.  There's build and run.  You need to provide whatever is necessary for setup.py to successfully run at build time.  Often times, run-time requirements are much more extensive than build-time requirements - these are things that are needed for all of the functionality in your package.

Please see the meta.yaml reference at https://conda.io/docs/building/meta-yaml.html

**Comment by arsenovic** [comment]
sorry bout that , i updated my issue.  
so, if i understand,  the package list in meta.yaml's `build` should  be what is in setup()'s `install_requires` (at the least), since conda doesnt use setuptools ?

**Comment by msarahan** [comment]
The safest thing is to copy your install_requires into both ``requirements/build`` and ``requirements/run``

You can cut things from either and see if it still works.

**Comment by arsenovic** [comment]
ok thanks. 

to put this in context, i am trying to put this package on conda-forge, but i [get a conflict](https://github.com/conda-forge/staged-recipes/pull/2323#pullrequestreview-20155037) which i dont know how to troubleshoot. the latency on cloud services makes trial and error removal of dependency packages  sloowww....
