### ISSUE TITLE
PDF download?

### ISSUE THREAD

**Issue by fommil** [conda/conda-docs#444]
I'd love to get a PDF version of https://conda.io/docs/ as per most readthedocs.org pages. But the link doesn't seem to be there, can you please make this available? It's very useful for offline reading with printed paper or an ereader.

**Comment by kerrywatson1** [comment]
We do plan to implement this in the next few months. In the interim, you can get a copy of the docs following this method: https://groups.google.com/a/continuum.io/forum/#!topic/conda/2PKXuXvZI1A
