### ISSUE TITLE
Possible Documentation error 

### ISSUE THREAD

**Issue by apiszcz** [conda/conda-docs#477]
https://conda.io/docs/user-guide/tasks/manage-environments.html

To remove an environment it seems conda env is required. The example at the bottom of the page omits that argument?

OLD?
conda remove --name myenv --all

NEW?
conda env remove --name myenv --all

**Comment by kerrywatson1** [comment]
Thanks, you're right, I've put in a PR for that:

https://github.com/conda/conda-docs/pull/478

**Comment by electronwill** [comment]
Fixed in https://github.com/conda/conda-docs/pull/478 .
