### ISSUE TITLE
Upload new conda 4.3.24 cheat sheet

### ISSUE THREAD

**Issue by kerrywatson1** [conda/conda-docs#479]
[conda-cheatsheet.pdf](https://github.com/conda/conda-docs/files/1252315/conda-cheatsheet.pdf)

**Comment by kerrywatson1** [comment]
@electronwill I think this goes in a generated directory that's not documented so please upload and update readme.md, thanks!

**Comment by electronwill** [comment]
Oops, forgot to close this issue. Done in https://github.com/conda/conda-docs/pull/481 .
