### ISSUE TITLE
Registered trademark symbol doesn't show correctly

### ISSUE THREAD

**Issue by BioGeek** [conda/conda-docs#496]
On page https://conda.io/docs/ the registered trademark symbol ® shows up correctly behind Anaconda in the fourth paragraph but shows up as |reg| in the sixth paragraph (when it is inside a 

I don't have Sphinx installed so I can't test this out, but moving the `|reg|` outside the hyperlink, like this:

```
:ref:`Anaconda<anaconda-glossary>`\ |reg| 
```
probably solves the problem

**Comment by electronwill** [comment]
Thank you very much for telling us! Fixed in https://github.com/conda/conda-docs/pull/503 .
