### ISSUE TITLE
Clarification about installing non-conda packages (e.g. with pip)

### ISSUE THREAD

**Issue by dietercastel** [conda/conda-docs#498]
I'd like to point out some conda behavior that imho is not well documented but can cause a lot head-scratching (at least on my part). So for future reference here goes: 

When installing non-conda packages e.g. with pip it's very important to be aware of whether the non-conda package manager you use is is installed inside or outside the environment. Both are in fact possible and a package manager inside an environment will have priority over the one outside the environment.

To use pip inside an environment you need to install pip like a regular package to the environment: [See this subsection in manage environments](https://conda.io/docs/user-guide/tasks/manage-environments.html?highlight=pip#using-pip-in-an-environment_). 

Only if using pip inside the environment will packages show up in `conda list` with indication that pip installed them similar to this:
```
Keras                     2.0.8                     <pip>
```

You can determine what pip you are using with `pip -v | grep envs`. See the example below:
```
dieter@machine:~/Documents/$ source activate testenvwithpip
(testenvwithpip) dieter@machine:~/Documents/$ pip -V | grep envs 
pip 9.0.1 from /home/dieter/miniconda3/envs/testenvwithpip/lib/python3.6/site-packages (python 3.6)
(testenvwithpip) dieter@machine:~/Documents/$ source deactivate
dieter@machine:~/Documents/$ source activate testenvnonpip
(testenvnonpip) dieter@machine:~/Documents/$ pip -V | grep envs
(testenvnonpip) dieter@machine:~/Documents/$ 
```

To update the docs I would suggest at least referencing [how to install pip inside an environment ](https://conda.io/docs/user-guide/tasks/manage-environments.html?highlight=pip#using-pip-in-an-environment) when discussing [installing non conda-packages](https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages). And maybe a bit more explanation like I did above. I'm creating a pull-request with recommended changes. If anything is unclear be sure to let me know.

**Comment by electronwill** [comment]
Fixed in https://github.com/conda/conda-docs/pull/506 .
