### ISSUE TITLE
custom private channel no arch directory not found

### ISSUE THREAD

**Issue by fvisconti** [conda/conda-docs#531]
Hi,

I have a custom channel on a private server, added in `.condarc` as 
`http:USER:PASSWD@server.url`.

It has been working for a long time, but now it says:

`WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/http:USER:PASSWD@server.url`.

Of course the `noarch/repodata.json` and associated `noarch/repodata.json.bz2` files are there, as have always been.

I feel it is strange the `conda` url is prepended to my custom url, what's going on?

It's a WARNING, so everything runs fine unless I need a package from my channel.

```
conda --version
conda 4.4.7
```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda#6771
