### ISSUE TITLE
activate command doesnt work

### ISSUE THREAD

**Issue by jayjagtap** [conda/conda-docs#532]
Windows 10, Ananconda 3.5.

I was trying to install tensorflow with anaconda. The environment is succesfully created.
But when I fire activate tensorflow, the following text is displayed. I have absolutely no idea, what is going wrong.
 
Note: I get the same results with anaconda prompt , cmd, powershell and even cygwin.

![image](https://user-images.githubusercontent.com/32436613/35474890-98cf4ffa-03ba-11e8-81e6-46dc64a572e0.png)

**Comment by kalefranz** [comment]
Try ‘conda update conda’ and see if that fixes your problem.

**Comment by jayjagtap** [comment]
Done. Thank You so much. What was exactly wrong?

**Comment by kalefranz** [comment]
Bug that was fixed in conda 4.4.8.
