### ISSUE TITLE
for pure Python recipes, list reqs in host section, not build section

### ISSUE THREAD

**Issue by electronwill** [conda/conda-docs#550]
Flowdock conversation 2018-02-16:
Jonathan: For pure python recipes, is it preferable to list requirements in the host or build section?  As conda-forge moves to cb3 I expect this questions to come up often.
Ray: host
Ray: build is for build tools
Jonathan: I agree with this, but I want to discuss it a bit more as I expect that some conda-forge folks will disagree
Jonathan: Some arguments for build only recipes vs host only recipes would be:
1) 1000's of recipes currently have build section that would need to be changed.
2) host only recipes do not work with conda build 2
3) the example in the documentation (https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#build) gives python in the build section and mentions that numpy should be listed there as well

Ray: 1) The change is simple and only needs to be done when you're updating.
2) I care about this as much as I do about conda-build 1 compat and CF should likewise.
3) We should fix that.
Ray: On 2. they update their CI infra and that's that, there's no halfway house.

@mingwandroid , would you please create a PR with the corrections to https://github.com/conda/conda-docs/blob/master/docs/source/user-guide/tasks/build-packages/define-metadata.rst and tag @cio-docs to review, or see if someone else on the team can draft it?

cc @jjhelmus

**Comment by mingwandroid** [comment]
https://github.com/conda/conda-docs/pull/551/files

**Comment by electronwill** [comment]
Thank you! PR drafted in https://github.com/conda/conda-docs/pull/551 .

**Comment by electronwill** [comment]
Done in https://github.com/conda/conda-docs/pull/551 .
