### ISSUE TITLE
Dead link to Conf. Advanced Features

### ISSUE THREAD

**Issue by michaelaye** [conda/conda-docs#577]
On the page:

https://conda.io/docs/user-guide/configuration/use-condarc.html

there's a broken link to:

https://continuum.io/blog/advanced-conda-part-1#configuration

in the section:

https://conda.io/docs/user-guide/configuration/use-condarc.html#overview

**Comment by electronwill** [comment]
Thank you for telling us! Removed in https://github.com/conda/conda-docs/pull/608 .
