### ISSUE TITLE
Add a user-facing section about features and their trouble-shooting

### ISSUE THREAD

**Issue by michaelaye** [conda/conda-docs#579]
Currently, `features` are only being discussed in the section `Tasks->Building packages`. As a user that never built a package, I always skipped that section and wasn't aware of `features` at all, which prevented me from understanding the bugs caused by their existence (and me not configuring them).
I think we urgently need a user-focused section of `features` so that all users are aware of them and can troubleshoot them.

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda-build/en/latest/concepts/features.html#features

**Comment by michaelaye** [comment]
this is documentation for conda-build only, while the described issue comes from not knowing about `features` but creating a lot of issues when basing an environment on pure conda-forge. Without forcing things like numpy to come from conda-forge, the `features` feature starts to mix packages from `defaults` and `conda-forge` leading to user-side errors, even so they never touch conda-build.

**Comment by msarahan** [comment]
Is this really still true?  We have pretty much eradicated all use of
"features" in defaults.  The only remaining use of track_features is as a
hack to allow default selection of a particular variant.  If you're still
having problems with features, please post your use case that precipitates
the problem.

**Comment by michaelaye** [comment]
Oh I wouldn’t know because I never heard of any fixes related to this so I never removed my workarounds. Will see what happens if I remove my package pinnings to conda-forge and report back if there’s still an issue.
