### ISSUE TITLE
"Edit on GitHub" bad URL

### ISSUE THREAD

**Issue by SeaDude** [conda/conda-docs#581]
Hello, 

There appears to be an extra " / " in the "Edit on GitHub" URL: 

`https://github.com/conda/conda-docs//master/docs/source/help-support.rst`. 

The link goes to a "Not Found" page. Sorry i'm lame and don't know how to fix it myself (though I am adding a PR to the docs themselves!)

**Comment by soapy1** [comment]
Should be fixed now!
