### ISSUE TITLE
update building packages with skeleton tutorial

### ISSUE THREAD

**Issue by kajiglet** [conda/conda-docs#591]
The [skeleton tutorial](https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html) uses pyinstrument as the example PyPI package. That package now has a C extension dependency so the package creation will fail without first packaging it. Also, the auxiliary build scripts (build.sh and bld.bat) are unnecessary as they are replaced by the meta.yaml build/script section. These issues lead to immediate confusion when following the tutorial.

**Comment by rrigdon** [comment]
That tutorial has been updated to exclude pyinstrument and now have Click as the example. https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html
