### ISSUE TITLE
Building a SEP package with conda and Python fails

### ISSUE THREAD

**Issue by spara** [conda/conda-docs#602]
**version:** conda 4.5.9
**description:** 
```
conda skeleton pypi sep
``` 
Creates a meta.yaml file with a build section.  Tutorial says add bld.bat and build.sh in the tutorial. The build section in meta.yaml file conflicts with build.sh and build fails.

```
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "
```

**Comment by msarahan** [comment]
Out of date docs.  The skeleton generator has changed since the docs were written, and no longer outputs build.sh/bld.bat.  Instead, it has one line in meta.yaml that works for both.  Creating build.sh definitely conflicts with the created recipe.

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/building-conda-packages.html#building-a-sep-package-with-conda-and-python-2-or-3
