### ISSUE TITLE
document conda strict channel priority

### ISSUE THREAD

**Issue by electronwill** [conda/conda-docs#611]
Previously if a user had conda-forge as the top channel and defaults below it, and the solver couldn't find a certain package in conda-forge, it might reach into defaults for the package. In some cases such as build scripts it's better to fail with an error, so this has now been made an option as "strict channel priority", and the previous behavior is now known as "flexible channel priority". cc @kalefranz

**Comment by rrigdon** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#strict-channel-priority
