### ISSUE TITLE
The version of Python is 3.6.5 when i run command "python -V" in my Python2 environment

### ISSUE THREAD

**Issue by creatist** [conda/conda-docs#614]
I installed Anaconda3 on windows10, and I have created a  Python2 environment. When i run command "python -V" in the Python2 environmnet, i got the output "Python 3.6.5".  Anyone can help me ? please.

**Comment by kumar432** [comment]
Yes, try to prifix python =="version" in your new environment which you wish to create.Thank you .I hope You solved.
