### ISSUE TITLE
Incorrect "conda index" command example

### ISSUE THREAD

**Issue by darren-c** [conda/conda-docs#617]
Using **conda 4.5.11 Python 3.7.0**

From the "Create Custom Channels" page:
https://conda.io/docs/user-guide/tasks/create-custom-channels.html

In step 3, the command shown for "conda index" shows as

> conda index channel/linux-64 channel/osx-64

and the instructions say to specify each subdirectory.

However if you do this, you get the following message:

> The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.

The command should be:

> conda index channel

where "channel" is the root directory that contains all your platform subfolders

**Comment by rrigdon** [comment]
Updated.
