### ISSUE TITLE
Conda cheat sheet says "create env --file some.txt" but it should be "create --file some.txt"

### ISSUE THREAD

**Issue by filo-paa** [conda/conda-docs#621]
As title: the official Conda pdf Cheat Sheet (conda-docs/docs/source/user-guide/conda-cheatsheet.pdf) says that in order to _create a new environment from file_ from a file i prevoiusly generated, the line command should be:
`conda env create --file myfile.txt`
, but it gives an enormus amount of tracebacks and it does not work at all. Instead i found working:
`conda create --file myfile.txt`
, so essentially: it worked removing "env".
I don't think it's an error of conda env, i think you just need to correct the pdf at the line:

> Create environment from a text file                conda env create --file bio-env.txt

, so in the end the line should become:

> Create environment from a text file                conda create --file bio-env.txt

let me know if i'm correct! Cheers.

**Comment by rrigdon** [comment]
We've since updated the cheat sheet.
