### ISSUE TITLE
miniconda2 "python: Permission denied" installation issue 

### ISSUE THREAD

**Issue by laninsky** [conda/conda-docs#622]
Hi folks,

Using the Linux 64-bit installer for Miniconda2 I encountered the following error:
```
installing: python-2.7.15-h1571d57_0 ...
Miniconda2-latest-Linux-x86_64.sh: line 370: /nesi/nobackup/uoo02424/bin/test/pkgs/python-2.7.15-h1571d57_0/bin/python: Permission denied
```
I solved it by tweaking the following in comparison with the original installation script:
```
6,7c6,7
< # BYTES: 41787802
< # LINES: 512
---
> # BYTES:     41787735
> # LINES: 511
168,169c168,169
< if ! wc -c "$THIS_PATH" | grep     41787802 >/dev/null; then
<     printf "ERROR: size of %s should be     41787802 bytes\\n" "$THIS_FILE" >&2
---
> if ! wc -c "$THIS_PATH" | grep     41787735 >/dev/null; then
>     printf "ERROR: size of %s should be     41787735 bytes\\n" "$THIS_FILE" >&2
328c328
< MD5=$(tail -n +512 "$THIS_PATH" | md5sum -)
---
> MD5=$(tail -n +511 "$THIS_PATH" | md5sum -)
340,341c340,341
< if ! tail -n +512 "$THIS_PATH" | tar xf -; then
<     printf "ERROR: could not extract tar starting at line 512\\n" >&2
---
> if ! tail -n +511 "$THIS_PATH" | tar xf -; then
>     printf "ERROR: could not extract tar starting at line 511\\n" >&2
370d369
<     chmod a+rwx "$PREFIX/pkgs/python-2.7.15-h1571d57_0/bin/python2.7"
```
Just posting here in case anyone else has been tripped up by this.

**Comment by laninsky** [comment]
I should add that mucking around with umask had not solved this issue.

**Comment by laninsky** [comment]
Hmmm... I'm going to further add that maybe it could be an issue to do with our cluster being overly restrictive on permissions of recently created files, but this could affect other folks with a similar set up too.

**Comment by sfarina** [comment]
same happened to me (amazon linux)

it's the install script permissions:
https://www.quora.com/Why-do-I-get-a-permission-denied-message-when-I-install-Anaconda-2-4-4-0-on-the-Mac
