### ISSUE TITLE
note that mac osx 10.9 SDK from https://github.com/phracker/MacOSX-SDKs is missing files

### ISSUE THREAD

**Issue by beckermr** [conda/conda-docs#623]
The osx sdk from https://github.com/phracker/MacOSX-SDKs is missing files compared to a full copy of it from xcode 6.4

**Comment by jakirkham** [comment]
xref: https://github.com/phracker/MacOSX-SDKs/issues/8

**Comment by beckermr** [comment]
You might add this link to the docs too? 

https://github.com/AaronWallace/MacOSX_SDKs

**Comment by beckermr** [comment]
pulled from issue above

**Comment by mingwandroid** [comment]
>  Thank you for reaching out, it given your very specific requirements, there are really not many with the skillset; have you ever considered a partnership with Anaconda? Our partner team might be able to make referrals."

There's absolutely nothing wrong with the phracker ones. Yes they are is missing files needed to statically link the macOS 10.6 SDK. That's hardly of any concern since static exes on macOS are unsupported and the macOS 10.6 SDK is older than any we want to use.

Those AaronWallace SDKs haven't been updated in years. Closing.

**Comment by mingwandroid** [comment]
And AD can be built in its entirety with the phracker SDKs. Do you have an actual issue to report here?

**Comment by mingwandroid** [comment]
Those CRT stubs are for GCC *anyway*. compiler-rt and libSystem implement the C runtime for clang.

**Comment by beckermr** [comment]
Ohhh ok sounds good! I am building gfortran which requires gcc so that probs explains how I ran into it. Thanks for your time!

**Comment by mingwandroid** [comment]
Ah hmm, yeah. Well, those files actually come with GCC as well, and infact that's where they belong.

The old GCC 4.8.5 includes them AFAIR.

Have you tried to build gfortran with clang btw? It should be possible I think!

**Comment by beckermr** [comment]
@mingwandroid I tagged you on a PR on staged-recipes for a start. We can discuss there!
