### ISSUE TITLE
TODO: move "silent installation" instructions into anaconda docs

### ISSUE THREAD

**Issue by msarahan** [conda/conda-docs#628]
I'm consolidating the conda docs while at the PyPA sprint.  I'm pointing the installation instructions to our instructions in the Anaconda docs.  The "silent installation" instructions in the Anaconda docs point back at the conda-docs here.  We should move the silent installation stuff to Anaconda-docs and have the conda-docs point there.

**Comment by csoja** [comment]
Is there anything else in the Miniconda installation instructions that should be added to the Anaconda Distribution docs?  I created a PR for Silent Installation from the content in the conda docs.  After it is merged, I'll go ahead and redirect the link to that page instead of the conda docs.
