### ISSUE TITLE
Latest Docker Image doesn't relate to a version number

### ISSUE THREAD

**Issue by rothwewi** [conda/conda-docs#630]
When i look at the tags on Docker hub for the miniconda (or miniconda3) images I can see a latest tag produced 18 days ago and a highest symbolic version number (4.5.11) produced a month ago. As latest has no meaning beyond 'current default' it seems sensible that it also has a specific version tag. 

Is there a reason it does not have a specific version tag?

**Comment by soapy1** [comment]
They should be the same version! We have fixed the issue. If you pulled latest or 4.5.11 previously you should have the same version of conda.
