### ISSUE TITLE
check available disk space before fill it and exit on failure

### ISSUE THREAD

**Issue by tuxun** [conda/conda-docs#640]
its always fun to discover a package needed more than 1.5 gb of dependencies on a unusable machine. (cause with a full hardrive we are unable to use bash autocompletion for remove these packages, for example)

**Comment by rrigdon** [comment]
Kamino closed and cloned this issue to [ContinuumIO/anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/issues/11256)
