### ISSUE TITLE
Julia 1.0.2 package installs old version

### ISSUE THREAD

**Issue by Fredo-XVII** [conda/conda-docs#645]
Hello,

When I install the Julia package with conda, conda installs Julia 1.0.0, even though it says 1.0.2 on the package website.  See below.

https://anaconda.org/conda-forge/julia

There are some important fixes in the new version, can you update the package to the current version? Can you make it so that I can use conda update julia so that it updates to the current version? Otherwise, I am going to have remove the current install and that has cause issues in the past where I have to remove the entire miniconda installation.  

Thanks,

Alfredo

**Comment by csoja** [comment]
This is the wrong place to log this issue - as the audience that looks at these is not responsible for the Julia conda-forge package.  Please log the issue here instead: https://github.com/conda-forge/julia-feedstock

**Comment by Fredo-XVII** [comment]
Sorry about that...thanks!
