### ISSUE TITLE
Issue with x86_64-conda_cos6-linux-gnu-gcc

### ISSUE THREAD

**Issue by TeamSeb** [conda/conda-docs#665]
Hi,

Not quite sure whether this is a conda issue.

When installing `Scalar::Util::Numeric` using `cpanm` and `miniconda3`, installation fails on gcc call below:
```
/tmp/build/80754af9/perl_1527832170752/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc -c  -I. -D_REENTRANT -D_GNU_SOURCE --sysroot=/tmp/build/80754af9/perl_1527832170752/_build_env/x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O3 -Wall -W   -DVERSION=\"0.40\" -DXS_VERSION=\"0.40\" -fPIC --sysroot=/tmp/build/80754af9/perl_1527832170752/_build_env/x86_64-conda_cos6-linux-gnu/sysroot "-I/home/user/miniconda3/lib/5.26.2/x86_64-linux-thread-multi/CORE"   Numeric.c
/bin/sh: 1: /tmp/build/80754af9/perl_1527832170752/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc: not found
```

but the command `which x86_64-conda_cos6-linux-gnu-gcc` returns:
`/home/user/miniconda3/bin/x86_64-conda_cos6-linux-gnu-gcc`

Why is the temporary folder used for compilation used to invoke x86_64-conda_cos6-linux-gnu-gcc?

Thanks for your help.

**Comment by TeamSeb** [comment]
Hi again,

I think I found a workaround to this by creating a symlink:
```
cd /tmp/build/80754af9/perl_1527832170752
ln -s /home/user/miniconda3/ _build_env
```

However, I would still like to know why is this temporary folder used.
Thanks again.

**Comment by stain** [comment]
The temporary build path is probably stuck inside the build configuration for cpanm (or more likely perl) as a config file -- some of the ruby distribution have similar issues. So they are issues in the recipes for the corresponding upstream packages.
