### ISSUE TITLE
Broken links/redirects from https://conda.io/docs (404)

### ISSUE THREAD

**Issue by stain** [conda/conda-docs#666]
Old link https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html redirects to https://conda.io/en/latest/user-guide/tasks/build-packages/compiler-tools.html which is 404
https://docs.conda.io/projects/conda-build/en/latest/source/resources/compiler-tools.html according to site-search.

Same story for https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html should go to  https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html (?) but the redirect goes to https://conda.io/en/latest/user-guide/tasks/build-packages/define-metadata.html which is 404

Example of pages who use(d) the `conda.io/docs` links: https://bioconda.github.io/cb3.html

**Comment by notestaff** [comment]
Still seems broken today?  First google hit for conda docs ends up with a 404 error.

**Comment by rrigdon** [comment]
Hi @stain! Thanks for bringing this to our attention. Those links should all be working now.
