### ISSUE TITLE
bunzip2 requirements to install miniconda

### ISSUE THREAD

**Issue by PhilLAL** [conda/conda-docs#669]
Hi,
trying to install miniconda, I noticed that bunzip2 is needed, it is included into bzip2 package in debian.
Perhaps a note about this dependency should be added?
Regards.

**Comment by rrigdon** [comment]
Kamino cloned this issue to [conda/conda-docs](https://github.com/conda/conda-docs/issues/687)

**Comment by msarahan** [comment]
This is no longer true as of the Anaconda 2019.07 release.  Closing.
