### ISSUE TITLE
NAVIGATION ERROR...

### ISSUE THREAD

**Issue by cmorris2945** [conda/conda-docs#684]
Please help with this error. Everytime I try to open my anaconda navigator, this pops up...

![Screenshot (126)](https://user-images.githubusercontent.com/30676606/63570918-a2248700-c54c-11e9-9ed1-3f938b2da7d2.png)

**Comment by csoja** [comment]
Looks like your .condarc file has gotten corrupted.  It is probably located at C:\Users\chris\.condarc
If you delete it and then attempt to open Anaconda Navigator again you may have better luck.

**Comment by cmorris2945** [comment]
What can I say...you're amazing!Exactly as you said. I deleted it, and it launched like normal.
Thank you!
What is the .condarc file?Why does it get corrupted?Is that what would normally cause this to happen...corruption of the .condarc file?
-CHRIS
"Sports, football, beer and above all gambling, filled up the horizons of their minds. To keep people in control and ignorant was not difficult...."  
- George Orwell,  author:'1984'
 

    On Friday, August 23, 2019, 10:30:30 AM EDT, csoja <notifications@github.com> wrote:  
 
 
Looks like your .condarc file has gotten corrupted. It is probably located at C:\Users\chris.condarc
If you delete it and then attempt to open Anaconda Navigator again you may have better luck.

**Comment by rrigdon** [comment]
Feel free to check out more info about our .condarc files: https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html
