### ISSUE TITLE
Duplicated contributing page is out of sync with conda/conda

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-docs#745]
This repo lists a [`contributing.rst` file](https://github.com/conda/conda-docs/blob/0e3546c/docs/source/contributing.rst) that is shown in the [conda.io website](https://docs.conda.io/en/latest/contributing.html). 

`conda/conda` has [a very similar one which has been recently updated](https://github.com/conda/conda/blob/b2b93dc/CONTRIBUTING.md) and is not shown in any website (fix for that in https://github.com/conda/conda/pull/11041).

I suggest both are integrated, `conda/conda` being the source of truth.

**Comment by jezdez** [comment]
I like that idea, thanks for raising this @jaimergp!

**Comment by jaimergp** [comment]
11041 now contains the CLA iframe too so this one can be removed. For SEO reasons the link should still point to the conda/conda one though.

**Comment by jezdez** [comment]
For the record, we removed the iframe in conda/conda a while ago since it didn't fully work for various reasons on all browsers and GitHub also doesn't render it as part of the regular page rendering. It's okay to have it simply linked from the document.

**Comment by travishathaway** [comment]
@jezdez, if we consolidate our docs to a single docs site, does this render this ticket defunct (like we are planning to do here: #777)?  If so, it would be nice to close this issue.

**Comment by jezdez** [comment]
Yeah, that's the plan, but I only wanted to close it when we actually combine it.

**Comment by jaimergp** [comment]
Not stale.

**Comment by travishathaway** [comment]
@jaimergp,

This pull request:
- https://github.com/conda/conda-docs/pull/900

makes it so that the two landing pages are different. Therefore, this sort of sync doesn't need to be setup. Once that is merged then this issue will be considered complete.
