### ISSUE TITLE
Revamp Sphinx theme

### ISSUE THREAD

**Issue by jezdez** [conda/conda-docs#750]
We use the custom conda Sphinx theme in a number of repos which makes it much harder to update the way the docs look like.

As a first step we should move the Sphinx theme in a separate repo, e.g. conda-sphinx-theme, and enable it in all repos that make up conda.io. This work is in preperation of #747 and other related issues.

**Comment by jaimergp** [comment]
Not stale.

**Comment by travishathaway** [comment]
@jezdez, please create a conda-sphinx-theme repo in the conda-incubator organization.

**Comment by travishathaway** [comment]
New theme has been created here: https://github.com/conda-incubator/conda-sphinx-theme

**Comment by travishathaway** [comment]
Considering this new repository has been created, I am considering this issue complete.

Work for actually using this theme for individual projects will be tracked in other issues. See https://github.com/conda/conda-docs/issues/776 for a full list.
