### ISSUE TITLE
M1 64-bit: Sorry this page does not exist yet

### ISSUE THREAD

**Issue by eas342** [conda/conda-docs#751]
I went to the miniconda page to download the M1 61-bit bash

https://docs.conda.io/en/latest/miniconda.html

When I click the link: https://docs.conda.io/en/latest/Miniconda3-latest-MacOSX-arm64.sh

It says "SORRY This page does not exist yet." Is it still under development?

**Comment by eas342** [comment]
If I scroll down and open this link, it works though

https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.1-MacOSX-arm64.sh

**Comment by csoja** [comment]
Thanks for the error report. A fix for this is now merged, and should be available soon.  See: https://github.com/conda/conda-docs/pull/752
