### ISSUE TITLE
Miniconda SHA-256 is unavailable

### ISSUE THREAD

**Issue by yummy-000** [conda/conda-docs#755]
This could be an error on my end, but the Miniconda hashes found [here](https://conda.io/en/latest/miniconda_hashes.html) seem to be missing when displayed on the webpage.

The hash information is still available in the [github](https://github.com/conda/conda-docs/blob/master/docs/source/miniconda_hashes.rst) source, and also [here](https://repo.anaconda.com/miniconda/) as MD5 hashes.

Preview, using Google Chrome:
![image](https://user-images.githubusercontent.com/96549666/147156312-9094fabb-6459-418c-82a4-41f2c7242a29.png)

**Comment by csoja** [comment]
Thank you for the error report! I see the same behavior.  We need to look into it.  Thanks again for reporting the issue.
