### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by priyambial123** [conda/conda-docs#760]
Hello

I created conda environment in the HPC and installed lockfile, mamba, snakemake using the command: 

> conda create -n pacbio-human-wgs -c bioconda -c conda-forge lockfile==0.12.2 python=3 snakemake mamba

When I activate the environment and run script, I get the below error:

> Building DAG of jobs...
> Creating conda environment workflow/rules/envs/mosdepth.yaml...
> Downloading and installing remote packages.
> CreateCondaEnvironmentException:
> Could not create conda environment from /scicore/workflow_pacbio/workflow/workflow/rules/envs/mosdepth.yaml:
> RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/noarch/repodata.json]
    Failed to connect to conda.anaconda.org port 443 after 5101 ms: Connection timed out

I tried installing the modules given in the yaml file in the conda environment, but I still get the above error.  Has anyone come across this error. 

What is causing the run time error here.

Thanks

Priya

**Comment by jezdez** [comment]
Hi Priya, this is off-topic for this repo which contains the conda documentation.
