### ISSUE TITLE
Potential mistake in the documentation [CLA page]

### ISSUE THREAD

**Issue by pranay-ar** [conda/conda-docs#768]
Hello, I was setting up the conda development environment as suggested on the [contributor's page](https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement) and noticed that to add a connection record to the remote repository, it is suggested in the docs to execute:

`git remote --add upstream git@github.com:conda/conda` which returns an error. 

Whereas I believe it should be, 

`git remote add upstream git@github.com:conda/conda`

A screenshot displaying the above issue is shown below:

![conda_mistake](https://user-images.githubusercontent.com/47575027/158845556-43ba015f-ed44-4481-876d-d5bbb8cf9271.png)

**Comment by kenodegard** [comment]
Thanks for pointing this out!
