### ISSUE TITLE
Update Miniconda installer links to Conda 4.12.0

### ISSUE THREAD

**Issue by EwoutH** [conda/conda-docs#775]
Could [miniconda.rst](https://github.com/conda/conda-docs/blob/master/docs/source/miniconda.rst) be updated with installer links for [Conda 4.12.0](https://github.com/conda/conda/releases/tag/4.12.0)?

**Comment by jezdez** [comment]
Miniconda hasn't been released yet with conda 4.12.0, but is planned to be done soon.

**Comment by azawalich** [comment]
@jezdez is there any date when the release will be?

**Comment by EwoutH** [comment]
It looks like Miniconda 4.12.0 was released yesterday! https://repo.anaconda.com/miniconda/

**Comment by skalburgi** [comment]
@EwoutH Miniconda 4.12.0 does not have python3.10 support yet, but the subsequent Miniconda release should support python 3.10 build.

**Comment by jezdez** [comment]
Fixed in b65d9f3feb23aeccef88af138ad8d910396e55cc.

**Comment by joelostblom** [comment]
A Miniconda installer with Python 3.10 would be convenient for teaching since novice students would have access to the improved Python error message without updating their Python version first. Are there plans to release this soon together with the new conda version 4.13 or 4.14?
