### ISSUE TITLE
How to create a package with the "new" file ending `.conda`?

### ISSUE THREAD

**Issue by jugmac00** [conda/conda-docs#796]
Hi,

here you can read:
https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format

> The .conda file format was introduced in conda 4.7 as a more compact, and thus faster, alternative to a tarball.

But it is not mentioned how.

The link behind "Read more about the [introduction of the .conda file format](https://www.anaconda.com/understanding-and-improving-condas-performance/)." just points to a press release/blog post, but no instruction.

a) is `.conda` the new default fileending?
b) how can I create a build with that fileending?

When I run `conda-build` I get a `*.tar.bz2` file.

**Comment by kathatherine** [comment]
To answer your main questions: 

1. No, it's not the new default. It's just another option.
2. Right now, I believe you can only create .conda files by transmuting them from the tar.bz2 files. See https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-packages/#conda-compression-format for a bit of info on that.

@chenghlee, anything else to add?

**Comment by dholth** [comment]
```
conda_build:
  # ... other options
  pkg_format: 2
  ```

**Comment by hmaarrfk** [comment]
Took me a while to figure out how to set "subkeys".

```bash
conda config --set conda_build.pkg_format 2
conda config --set conda_build.zstd_compression_level 19
```

can help you get going to same defaults as conda-forge
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/main/recipe/conda_forge_ci_setup/build_utils.py#L29
