### ISSUE TITLE
Dead link on https://docs.conda.io/en/latest/help-support.html

### ISSUE THREAD

**Issue by akapocsi** [conda/conda-docs#798]
The link to the [archived announcements](http://us13.campaign-archive1.com/home/?u=28f85eefa68de727efcbd93f9&id=cb4ca49e7d) near the bottom of the [help and support page](https://docs.conda.io/en/latest/help-support.html) is invalid.

**Comment by akapocsi** [comment]
This issue was closed prematurely.

**Comment by kathatherine** [comment]
Closed via https://github.com/conda/conda-docs/pull/932.
