### ISSUE TITLE
Outdated copyright

### ISSUE THREAD

**Issue by akapocsi** [conda/conda-docs#799]
The copyright date in the footer of the docs has not been updated in ~5 years. This may lead users to believe that the project is abandoned or no longer maintained.

https://github.com/conda/conda-docs/blob/master/docs/source/conf.py#L5
<img width="1056" alt="Screen Shot 2022-06-14 at 11 13 00 AM" src="https://user-images.githubusercontent.com/8197282/173613296-29e08339-e887-487f-9190-fb313db20894.png">

**Comment by kathatherine** [comment]
Hi, thank you so much for bringing this up. The copyright dates need to stay as they are because that's when the documents were created: see [here](https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#why-not-bump-the-year-on-change) and [here](https://opensource.google/documentation/reference/copyright) for the logic on this.

However, I agree that this makes the documents seem out of date or abandoned. An "Updated on <date>" or something similar for each file would give the reader/maintainers that info and leave the copyright as it is.

**Comment by mukul314** [comment]
Hey @kathatherine do you mean something like this?

<img width="288" alt="2023-04-03 13_27_58-Miniconda — conda documentation - Brave" src="https://user-images.githubusercontent.com/76463001/229447435-5489bec5-a656-403d-acb2-87bb69f52912.png">

**Comment by kathatherine** [comment]
Yes, something like that. Where did you get that screenshot? One of the Anaconda docs, it looks like.

**Comment by mukul314** [comment]
> Yes, something like that. Where did you get that screenshot? One of the Anaconda docs, it looks like.

Actually i was just playing around with the minocnda.html file and tweaked it a little bit.
Does the conda team have a url of some sort so that we can request it and get the latest status the site?

**Comment by mukul314** [comment]
Hey @kathatherine, I had a little doubt. I made a build directory and previewed my changes, now I have to push my changes , but the build directory was not there initially, so only the changes in the ".rst" file will be pushed ??

**Comment by kathatherine** [comment]
Of course, I forgot that there's an Anaconda copyright down there in the conda docs. Most likely what would need to happen is using a sphinx extension to grab a last updated timestamp from git itself. Something like https://github.com/mgeier/sphinx-last-updated-by-git or https://github.com/jdillard/sphinx-gitstamp. Probably worth some research.

**Comment by mukul314** [comment]
> Of course, I forgot that there's an Anaconda copyright down there in the conda docs. Most likely what would need to happen is using a sphinx extension to grab a last updated timestamp from git itself. Something like https://github.com/mgeier/sphinx-last-updated-by-git or https://github.com/jdillard/sphinx-gitstamp. Probably worth some research.

okay ! I'm on it, thanks!!!

**Comment by mukul314** [comment]
<img width="255" alt="2023-04-09 16_56_50-Miniconda — conda documentation - Brave" src="https://user-images.githubusercontent.com/76463001/230769857-67f7c1ac-8c12-4fb5-acc5-3e4eb28b11aa.png">

What should be the time format ??

**Comment by mukul314** [comment]
> 24-hour makes sense to me. If you have a PR ready, could you please push it and mention this issue in its description? We could discuss the particulars in the PR then.

Okay!!
