### ISSUE TITLE
Add sphinx-sitemap to the conda docs projects

### ISSUE THREAD

**Issue by jezdez** [conda/conda-docs#810]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Add the sphinx-sitemap extension to the conda-docs, conda and conda-build Sphinx projects.

### Why is this needed?

In preparation to refactor and improve the documentation, it would go a long way of having access to the full sitemap of the conda docs. With the server-side redirects set up on ReadTheDocs, we would have a list of URLs to make sure to exist in the future.

### What should happen?

`sitemap.xml` files accessible publicly under docs.conda.io and its subprojects.

### Additional Context

- https://github.com/conda/conda/pull/11697
- https://github.com/conda/conda-build/pull/4555
- https://github.com/conda/conda-docs/pull/813

**Comment by kathatherine** [comment]
We planning on doing this for the conda-docs repo as well?

**Comment by kathatherine** [comment]
@jezdez We planning on doing this for the conda-docs repo as well?
