### ISSUE TITLE
Delete `gh-pages` branch

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-docs#812]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Let's delete the `gh-pages` branch.

### Why is this needed?

This is an old stale branch that is no longer used for our docs (last updated in 2019).

### What should happen?

Delete the branch (and branch protections).

**Comment by jezdez** [comment]
Done!
