### ISSUE TITLE
Broken links: "Building a conda package"

### ISSUE THREAD

**Issue by OverLordGoldDragon** [conda/conda-docs#820]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

https://enterprise-docs.anaconda.com/en/latest/data-science-workflows/packages/build.html

 - [installing conda build](https://conda.io/projects/conda-build/en/latest/source/install-conda-build.html)
 - [conda build recipe](https://conda.io/projects/conda-build/en/latest/source/recipe.html)

**Comment by kathatherine** [comment]
Thank you for finding this issue! Those pages still exist, but the URLs have changed quite a bit. I luckily have access to the Anaconda Enterprise docs source code, so I was able to update those links. In the future, please report any issues with Anaconda documentation in either [Anaconda Issues](https://github.com/ContinuumIO/anaconda-issues) or the [Nucleus community forums](https://community.anaconda.cloud/c/feedback), as the conda GitHub organization doesn't contain the Anaconda docs.
