### ISSUE TITLE
conda with different versions of python

### ISSUE THREAD

**Issue by zyzhang1992** [conda/conda-docs#826]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have anaconda with python 3.9 and created python environments with different versions of python, for example python 3.8. However, when I activate an env created with python 3.8, python looks for packages both in the 3.9 env and the 3.8 environment. That often leads to conflicts and inconsistencies of packages installed in different versions of python. Is there a way to make sure that all the packages needed in an env be from a single version of python?

**Comment by beeankha** [comment]
Hi @zyzhang1992 , thank you for filing this issue!

I tried to recreate this issue on the latest version of conda and did not see the same results. However, if you prefer not to upgrade to the latest version of conda, one quick workaround for the problem that you're encountering would be to specify the Python version along with the package you want to install (e.g., `conda install [package] python=3.8` if you want the package to be compatible with Python 3.8). 

Please let us know if that fixes your issue. Also, this is the repo for conda documentation, so if there is a specific documentation page that should include this information, then please link to that docs page in your reply.

**Comment by zyzhang1992** [comment]
Thanks for the updates. I'll try that and then get back to you.
________________________________
