### ISSUE TITLE
Miniconda installer script declared as #!/bin/sh but syntax is bash

### ISSUE THREAD

**Issue by mfeblowitz** [conda/conda-docs#836]
When run as `miniconda.sh -b -p miniconda`  the error appears as:
```
Installing * environment...

./miniconda.sh: 444: ./miniconda.sh: [[: not found
```

The problem is resolved when miniconda.sh is modified to begin with `/bin/bash` or when invoked as `bash miniconda.sh -b -p miniconda`.

ubuntu 18.04
install url https://repo.anaconda.com/miniconda/Miniconda3-py38_22.11.1-1-Linux-x86_64.sh (and others)

**Comment by dbast** [comment]
see also https://github.com/conda/constructor/issues/596 and https://github.com/conda/conda/issues/10431

**Comment by rootsmusic** [comment]
@mfeblowitz This repo is to edit [conda documentation](https://github.com/conda/conda-docs#readme).

**Comment by jezdez** [comment]
This is off-topic and also has been fixed.
