### ISSUE TITLE
Broken link in /docs/source/admin.rst

### ISSUE THREAD

**Issue by Maggie-M** [conda/conda-docs#84]
Below the fifth paragraph on this page, there is a broken link in the text:

"See also: [Conda configuration file](http://conda.pydata.org/docs/config.html/)."

**Comment by asmeurer** [comment]
@electronwill @kerrywatson1 

Not only is the link broken, but we should never use a full url for an internal reference. It should always be a cross-reference so that it generates the link automatically.

**Comment by electronwill** [comment]
Am fixing this now.

**Comment by electronwill** [comment]
OK, pull request #86 should fix this.

**Comment by electronwill** [comment]
@Maggie-M @asmeurer Oops, we never closed this issue-- it's fixed and can be closed now, though.
