### ISSUE TITLE
Incorrect SHA256 hash?

### ISSUE THREAD

**Issue by gihanmarasingha** [conda/conda-docs#840]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I download the Windows 64-bit Miniconda 3 (from 'Latest Miniconda Installer Links'), the computed SHA 256 hash is `D4517212C8AC44FD8B5CCC2D4D9F38C2DD924C77A81C2BE92C3A72E70DD3E907`.

However, the hash on the Download page is given as `2e3086630fa3fae7636432a954be530c88d0705fce497120d56e0f5d865b0d51`

I note that this is the same hash that is listed under 'Windows installers' for the Python 3.10 installer.

**Comment by dbast** [comment]
There is a pending PR that updates the hashes, see https://github.com/conda/conda-docs/pull/838

**Comment by dbast** [comment]
fixed by https://github.com/conda/conda-docs/pull/838
