### ISSUE TITLE
Miniconda website should include code block to download and install Miniconda

### ISSUE THREAD

**Issue by tristanengst** [conda/conda-docs#842]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

The Miniconda website [https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html) should include a code block to easily download and install Miniconda.

### Why is this needed?

Without this, installing Miniconda is annoying as I click the [https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html) site, realize I need to download the installer script, and then have to find the code to do this somewhere else.

### What should happen?

The website showing how to install miniconda ([https://docs.conda.io/en/latest/miniconda.html](https://docs.conda.io/en/latest/miniconda.html)) should show how to do it with command-line only access. Other websites show how to do this, eg. by prominently including the code block
```
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh
```

### Additional Context

It is often necessary to install conda on systems with only command-line access.

**Comment by tristanengst** [comment]
I think it makes sense to have a "Quick Command Line Install" heading directly between the "See if Miniconda is right for you" link and the "System requirements" heading, and put the code blocks there for the latest Linux and macOS installers there, eg.
### Quick Command Line Install
**Linux**
```
CODE BLOCK
```
**macOS**
```
CODE BLOCK
```
- This will be prominent and not require any scrolling to see, so it will be fast to see and easy to copy and paste from.
- While I see an argument for putting the system requirements section first, the section is potentially too big to have all of the proposed quick command line install section be visible (and thus copyable) without scrolling, so I think the cost of putting the system requirements section first is inordinately high.
- Note the absence of SHA256 hashes. They should stay with the existing install links below—here, they would just be visual clutter and very unlikely to be needed.

This is probably the minimum change needed to solve the issue.

With this in mind, it might make sense to replace the command line install links that download a .sh file you subsequently run, with code blocks akin to the ones above.

**Comment by mukul314** [comment]
<img width="289" alt="2023-04-05 09_17_31-Miniconda — conda documentation - Brave" src="https://user-images.githubusercontent.com/76463001/229976356-de0b972d-440f-4fea-b636-c7b30c12d13a.png">
This should do the job right?

**Comment by tristanengst** [comment]
Assuming the code blocks themselves work, then yes!

**Comment by mukul314** [comment]
Okay, got it!!
