### ISSUE TITLE
Can't install miniconda on the macOS Ventura 13.3 

### ISSUE THREAD

**Issue by farfrom-Alex** [conda/conda-docs#852]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Recently, I upgraded my macOS system to Ventura 13.3. However, when I tried to install Miniconda on my Mac, the version I was trying to install was incompatible with my current macOS version. Please tell how to fix the problem.

**Comment by jiang-rick** [comment]
I have the same problem with you? R U fix it now?

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager documentation. Thank you for understanding!
