### ISSUE TITLE
Miniconda 3 Failed to extract packages in W7

### ISSUE THREAD

**Issue by DD1233211234** [conda/conda-docs#856]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Miniconda 3 Failed to extract packages in Window 7
![未命名](https://user-images.githubusercontent.com/131966446/234838363-4effe43a-bc61-42b2-958b-6c026a521ba5.jpg)

**Comment by travishathaway** [comment]
Hi @DD1233211234,

For any issues related to Anaconda installers (Anaconda Distribution or Miniconda) please file them at this project:

- https://github.com/ContinuumIO/anaconda-issues/issues
