### ISSUE TITLE
miniconda install error 404: Not Found

### ISSUE THREAD

**Issue by ewang104** [conda/conda-docs#878]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Trying to install miniconda on cluster, got an error message 404 Not Found. 

$ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda3.sh --no-check-certificate
--2023-08-04 14:51:51--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 172.29.200.35
Connecting to repo.anaconda.com (repo.anaconda.com)|172.29.200.35|:443... connected.
WARNING: no certificate subject alternative name matches
        requested host name ‘repo.anaconda.com’.
HTTP request sent, awaiting response... 404 Not Found
2023-08-04 14:51:56 ERROR 404: Not Found.

### Linked Issues & PRs

- [ ] #

**Comment by rootsmusic** [comment]
@ewang104 This repo is for [conda documentation](https://github.com/conda/conda-docs#readme).

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager documentation. Thank you for understanding!
