### ISSUE TITLE
MiniConda incompatible with MacOS 13.5.1

### ISSUE THREAD

**Issue by dbassDEV** [conda/conda-docs#892]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I tried to download Miniconda to my 16inch M2 Max MacBook Pro and the installer says "This package is incompatible with this version of macOS."

I had been using Miniconda previously but had to factory default my Mac.... This issue is new to me and after checking GitHub, new on here as well. Any help is welcome.

### Conda Info

```shell
N/A
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

### Additional Context

N/A

**Comment by rootsmusic** [comment]
@dbassDEV This repo is for [conda documentation](https://github.com/conda/conda-docs#readme).

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager documentation. Thank you for understanding!
