### ISSUE TITLE
Startmenu Windows Anconda Prompt & Powershell Prompt are broken after installing Miniconda or Miniforge 3

### ISSUE THREAD

**Issue by Au2mater** [conda/conda-docs#913]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When installing Miniconda 3 or Miniforge 3 on Windows 
'**Anaconda Prompt**' and '**Anaconda Powershell Prompt**' launchers are broken.
Launching them does NOT successfully activate the base environment.
This is because, the 'Target' property of the command prompt shortcuts points to %LOCALAPPDATA%/**Anaconda3**/...
rather than  %LOCALAPPDATA%/**Miniconda3**/... and %LOCALAPPDATA%/**Miniforge3**/... 
Same issue applies to the Jupyter Notebooks and Spyder Start menu shortcuts when installing Miniconda3
To fix it the user has to manually edit the shortcuts to point at the correct installation path for the conda implementation.

**Comment by rootsmusic** [comment]
@Au2mater This repo is for [conda documentation](https://github.com/conda/conda-docs#readme).

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager documentation. Thank you for understanding!
