### ISSUE TITLE
Grammar errors in FAQ section

### ISSUE THREAD

**Issue by jim22k** [conda/conda-docs#92]
Updating Packages in the root environment, section 4
-------------
Original paragraph reads as follows:

With this pinned file, `conda update numpy` will keep numpy at 0.7.1, and `conda install scipy=0.14.0` will lead to an error. To force either of these, use the `-no-pin` flag, like `conda update numpy --no-pin`. The way pinning works is that the pined specs are included with each conda install, so subsequent commands without `--no-pin` will revert numpy back to the 1.7 series.

This paragraph should instead read:

With this pinned file, `conda update numpy` will keep numpy at 1.7.1:arrow_backward:, and `conda install scipy=0.14.0` will lead to an error. To force either of these, use the `--no-pin`:arrow_backward: flag, like `conda update numpy --no-pin`. The way pinning works is that the pinned:arrow_backward: specs are included with each `conda install` or `conda update` command:arrow_backward:, so subsequent commands without `--no-pin` will revert numpy back to the 1.7 series.

_Emojis added to highlight the changes_

Installation, section 5
-------------
Original reads:

After performing the above command you can create a new environments in the standard way (the scipy will be installed in all of them).

Should instead be:

After performing the above command you can create new environments in the standard way (scipy will be installed in all of them).

Installation, section 6
---------------
Original reads:

After performing the above command you can create a new environments in the standard way (the scipy in 0.12.0 version will be installed in all of them).

Should instead be:

After performing the above command you can create new environments in the standard way (scipy version 0.12.0 will be installed in all of them).

**Comment by asmeurer** [comment]
@electronwill @kerrywatson1

**Comment by kerrywatson1** [comment]
@asmeurer @jim22k PR submitted branch "edits requested by jim22k #96"
