### ISSUE TITLE
Is the docs warning still accurate?

### ISSUE THREAD

**Issue by Adam-D-Lewis** [conda/conda-docs#939]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I really appreciate conda store, and have been a user for some time.  Recently, I was trying to learn more about conda store by reading the docs, and I see a warning on the [ conda store docs site](https://conda.store/) saying "⚠️ We are in the process of revamping our docs, some pages may be incomplete or inaccurate. ⚠️"  

It has been there for some time (months).  Is it still the case that the docs are inaccurate and/or is there still active work being done to improve the docs?  Could you at least narrow down which docs are expected to be inaccurate?  At the moment, it suggests to me that I can't trust anything I read there which makes it more difficult to learn more about the conda store internals.

Thanks!

**Comment by kathatherine** [comment]
Hi, @Adam-D-Lewis, this repo is specifically for the landing page (and a few other minor things) for the [docs.conda.io](https://docs.conda.io/en/latest/) website. I know the repo naming conventions for all the various conda-related projects can be confusing!

You'd likely be better off posting this concern in the https://github.com/conda-incubator/conda-store repo. Thank you!
